/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Local persisted workbench state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkbenchState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requirement-baseline-selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RequirementBaselineSelectionRequest"];
                };
            };
            responses: {
                /** @description Requirement baseline selected locally */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Explicit confirmation or version validation failed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recognized-credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecognizedCreditRequest"];
                };
            };
            responses: {
                /** @description Idempotent existing declaration returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Local declaration created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid declaration */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recognized-credits/{identity}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecognizedCreditRequest"];
                };
            };
            responses: {
                /** @description Local declaration updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid or missing declaration */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Local declaration deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Declaration not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginConfigurationRequest"];
                };
            };
            responses: {
                /** @description DPAPI-protected login saved */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid login configuration */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Saved login cleared */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanRequest"];
                };
            };
            responses: {
                /** @description Persisted read-only plan */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest persisted read-only plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No plan */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Local redacted execution history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Execution history cleared */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{identity}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unknown execution resolved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unknown execution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SelectionExecutionRequest"];
                };
            };
            responses: {
                /** @description Explicitly confirmed single execution queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Confirmation or applicability check failed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancellation requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task cannot be cancelled */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{identity}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Observation finish requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task cannot be finished */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidate notice versions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        index_url?: string;
                    };
                };
            };
            responses: {
                /** @description Matching official notice pages downloaded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Official notice source could not be read */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/{identity}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notice confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Notice cannot be confirmed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timetable/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        timetable?: string;
                        term?: string;
                    };
                };
            };
            responses: {
                /** @description Timetable snapshot imported */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequirementBaselineSelectionRequest: {
            version: string;
            /** @description Must exactly equal version */
            confirmation: string;
        };
        RecognizedCreditRequest: {
            identity: string;
            /** @enum {string} */
            category: "innovation" | "social_practice" | "cultural_quality";
            credits: number;
            note: string;
            /** Format: date */
            recognized_on: string;
            linked_course_identity?: string;
        };
        RecognizedCredit: components["schemas"]["RecognizedCreditRequest"] & {
            baseline_version: string;
            linked_course_identity: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RequirementBaselineRequirement: {
            key: string;
            label: string;
            minimum: number;
            /** @enum {string} */
            unit: "credits" | "courses";
            source?: string;
            parent?: string;
            /** @enum {string} */
            constraint?: "" | "single_track";
            /** @enum {string} */
            evidence: "grade_records" | "grade_and_recognition" | "classification";
            contribution_keys?: string[];
            required_conditions?: string[];
        };
        RequirementBaseline: {
            version: string;
            title: string;
            authority: string;
            requires_explicit_selection: boolean;
            source_summary: string;
            applicability: string;
            coverage: string;
            disclaimer: string;
            selected_at?: string;
            manual_supplements?: string[];
            requirements: components["schemas"]["RequirementBaselineRequirement"][];
            category_mapping: {
                [key: string]: string | string[];
            };
        };
        LoginConfigurationRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        TaskRequest: {
            /** @enum {string} */
            operation: "connect" | "refresh-selection" | "refresh-timetable" | "refresh-progress" | "observe-navigation";
            context?: {
                [key: string]: unknown;
            };
        };
        PlanRequest: {
            goals: {
                [key: string]: unknown;
            }[];
        };
        SelectionExecutionRequest: {
            section_id: string;
            snapshot_id: string;
            /** @description Must exactly equal section_id */
            confirmation: string;
        };
        LoginConfiguration: {
            /** @enum {string} */
            state: "missing" | "configured" | "invalid";
            configured: boolean;
            masked_username?: string;
            message?: string;
        };
        Task: {
            id: string;
            operation?: string;
            /** @enum {string} */
            task_kind?: "observation" | "execution";
            state: string;
            progress?: {
                [key: string]: unknown;
            };
            error?: string;
        };
        CandidateNotice: {
            version_id: string;
            status: string;
            title?: string;
            term?: string;
            query_eligible?: boolean;
        } & {
            [key: string]: unknown;
        };
        Snapshot: {
            id: string;
            kind: string;
            term: string;
            profile_id?: string | null;
            notice_id?: string | null;
            source: string;
            source_at: string;
            created_at?: string;
            payload: {
                [key: string]: unknown;
            };
        };
        CompletedCourseFact: {
            code: string;
            name: string;
            category: string;
            credits: number;
        };
        RequirementProgress: {
            key: string;
            label: string;
            /** @enum {string} */
            unit: "credits" | "courses";
            source: string;
            parent: string;
            /** @enum {string} */
            constraint: "" | "single_track";
            rule_detail: string;
            minimum: number;
            confirmed_amount: number;
            confirmed_gap: number;
            /** @enum {string} */
            condition_status: "satisfied" | "not_satisfied" | "unknown";
            condition_detail: string;
            /** @enum {string} */
            reason: "confirmed_minimum_met" | "confirmed_below_minimum" | "grade_data_incomplete" | "recognized_credit_coverage_missing" | "classification_evidence_missing" | "outside_major_track_unconfirmed" | "required_subconstraint_unknown" | "required_subconstraint_not_satisfied";
            reason_detail: string;
            declared_amount?: number;
            estimated_amount?: number;
            estimated_gap?: number;
            declarations?: {
                [key: string]: unknown;
            }[];
            manual_review_required?: boolean;
            required_credits: number;
            completed_credits: number;
            remaining_credits: number;
            courses: components["schemas"]["CompletedCourseFact"][];
        };
        GraduationProgressReport: {
            generated_at?: string;
            baseline_version?: string;
            data_complete: boolean;
            coverage?: {
                [key: string]: string;
            };
            progress: components["schemas"]["RequirementProgress"][];
        };
        GraduationProgress: {
            /** @enum {string} */
            status: "ready" | "incomplete" | "missing" | "invalid" | "not_applicable" | "historical";
            report: components["schemas"]["GraduationProgressReport"];
            historical_report?: components["schemas"]["GraduationProgressReport"];
            reason?: string;
            snapshot?: components["schemas"]["Snapshot"];
        };
        WorkbenchState: {
            login_configuration: components["schemas"]["LoginConfiguration"];
            requirement_baselines: components["schemas"]["RequirementBaseline"][];
            selected_requirement_baseline: components["schemas"]["RequirementBaseline"] | null;
            recognized_credits: components["schemas"]["RecognizedCredit"][];
            profile: {
                [key: string]: unknown;
            } | null;
            confirmed_notice: {
                [key: string]: unknown;
            } | null;
            snapshots: {
                selection: components["schemas"]["Snapshot"];
                timetable: components["schemas"]["Snapshot"];
                progress: components["schemas"]["Snapshot"];
            };
            snapshot_changes: {
                selection: {
                    [key: string]: unknown;
                } | null;
                timetable: {
                    [key: string]: unknown;
                } | null;
                progress: {
                    [key: string]: unknown;
                } | null;
            };
            latest_plan: {
                [key: string]: unknown;
            } | null;
            graduation_progress: components["schemas"]["GraduationProgress"];
            stale: {
                selection: boolean;
                timetable: boolean;
                progress: boolean;
            };
            snapshot_status: {
                [key: string]: {
                    /** @enum {string} */
                    status: "current" | "historical" | "incomplete" | "missing";
                    reason: string;
                    source_at: string;
                };
            };
            academic_session: {
                state: string;
                browser: string;
                webvpn: string;
                last_verified_at: string;
            };
            active_task: components["schemas"]["Task"];
            execution_history: {
                [key: string]: unknown;
            }[];
            csrf_token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
