/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Local persisted workbench state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkbenchState"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginConfigurationRequest"];
                };
            };
            responses: {
                /** @description DPAPI-protected login saved */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid login configuration */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Saved login cleared */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanRequest"];
                };
            };
            responses: {
                /** @description Persisted read-only plan */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest persisted read-only plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No plan */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Local redacted execution history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Execution history cleared */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{identity}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unknown execution resolved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unknown execution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SelectionExecutionRequest"];
                };
            };
            responses: {
                /** @description Explicitly confirmed single execution queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Confirmation or applicability check failed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancellation requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task cannot be cancelled */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{identity}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Observation finish requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task cannot be finished */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidate notice versions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        index_url?: string;
                    };
                };
            };
            responses: {
                /** @description Matching official notice pages downloaded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Official notice source could not be read */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notices/{identity}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identity: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notice confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Notice cannot be confirmed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timetable/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        timetable?: string;
                        term?: string;
                    };
                };
            };
            responses: {
                /** @description Timetable snapshot imported */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginConfigurationRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        TaskRequest: {
            /** @enum {string} */
            operation: "connect" | "refresh-selection" | "refresh-timetable" | "refresh-progress" | "observe-navigation";
            context?: {
                [key: string]: unknown;
            };
        };
        PlanRequest: {
            goals: {
                [key: string]: unknown;
            }[];
        };
        SelectionExecutionRequest: {
            section_id: string;
            snapshot_id: string;
            /** @description Must exactly equal section_id */
            confirmation: string;
        };
        LoginConfiguration: {
            /** @enum {string} */
            state: "missing" | "configured" | "invalid";
            configured: boolean;
            masked_username?: string;
            message?: string;
        };
        Task: {
            id: string;
            operation?: string;
            /** @enum {string} */
            task_kind?: "observation" | "execution";
            state: string;
            progress?: {
                [key: string]: unknown;
            };
            error?: string;
        };
        CandidateNotice: {
            version_id: string;
            status: string;
            title?: string;
            term?: string;
            query_eligible?: boolean;
        } & {
            [key: string]: unknown;
        };
        Snapshot: {
            id: string;
            kind: string;
            term: string;
            profile_id?: string | null;
            notice_id?: string | null;
            source: string;
            source_at: string;
            created_at?: string;
            payload: {
                [key: string]: unknown;
            };
        };
        CompletedCourseFact: {
            code: string;
            name: string;
            category: string;
            credits: number;
        };
        RequirementProgress: {
            key: string;
            label: string;
            required_credits: number;
            completed_credits: number;
            remaining_credits: number;
            courses: components["schemas"]["CompletedCourseFact"][];
        };
        GraduationProgressReport: {
            generated_at?: string;
            baseline_version?: string;
            data_complete: boolean;
            progress: components["schemas"]["RequirementProgress"][];
        };
        GraduationProgress: {
            /** @enum {string} */
            status: "ready" | "incomplete" | "missing" | "invalid" | "not_applicable";
            report: components["schemas"]["GraduationProgressReport"];
            snapshot?: components["schemas"]["Snapshot"];
        };
        WorkbenchState: {
            login_configuration: components["schemas"]["LoginConfiguration"];
            profile: {
                [key: string]: unknown;
            } | null;
            confirmed_notice: {
                [key: string]: unknown;
            } | null;
            snapshots: {
                selection: components["schemas"]["Snapshot"];
                timetable: components["schemas"]["Snapshot"];
                progress: components["schemas"]["Snapshot"];
            };
            snapshot_changes: {
                selection: {
                    [key: string]: unknown;
                } | null;
                timetable: {
                    [key: string]: unknown;
                } | null;
                progress: {
                    [key: string]: unknown;
                } | null;
            };
            latest_plan: {
                [key: string]: unknown;
            } | null;
            graduation_progress: components["schemas"]["GraduationProgress"];
            stale: {
                selection: boolean;
                timetable: boolean;
                progress: boolean;
            };
            snapshot_status: {
                [key: string]: {
                    /** @enum {string} */
                    status: "current" | "historical" | "incomplete" | "missing";
                    reason: string;
                    source_at: string;
                };
            };
            academic_session: {
                state: string;
                browser: string;
                webvpn: string;
                last_verified_at: string;
            };
            active_task: components["schemas"]["Task"];
            execution_history: {
                [key: string]: unknown;
            }[];
            csrf_token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
